/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zsw_jni_sharedmemory1_PointerShared */

#ifndef _Included_com_zsw_jni_sharedmemory_PointerShared
#define _Included_com_zsw_jni_sharedmemory_PointerShared
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsw_jni_sharedmemory1_PointerShared
 * Method:    getPointer
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_zsw_jni_sharedmemory_PointerShared_getPointer
  (JNIEnv *, jobject);

/*
 * Class:     com_zsw_jni_sharedmemory1_PointerShared
 * Method:    restorePointer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zsw_jni_sharedmemory_PointerShared_restorePointer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
